### ISSUE TITLE
AIF Script errors

### ISSUE THREAD

**Issue by joecummings** [joecummings/cdse-covid#135]
```
[2022-01-11 08:57:28] INFO:__main__:READING: /nas/gaia/users/cummings/experiments/jan-11/output.json WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CVMR.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CV9X.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PKE.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PGR.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CA7I.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04ATFK.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04959L.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CA72.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04958P.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049P8R.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PDL.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PGH.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04958U.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049DQS.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CAAI.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PDL.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04ATFF.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04CVOE.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049PHR.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049597.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04ATGI.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04ATLD.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C049DTI.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04958M.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C0495AW.ttl
[2022-01-11 08:57:29] INFO:__main__:WRITING: /nas/gaia/users/cummings/experiments/jan-11/aif_output/L0C04ATMN.ttl
Traceback (most recent call last):
  File "/nas/home/cummings/repos/cdse-covid/cdse_covid/pegasus_pipeline/ingesters/convert_claim_json.py", line 519, in <module>
    parameters_only_entry_point(convert_json_file_to_aif)
  File "/nas/gaia/lestat/users/cummings/miniconda/envs/covid-claims/lib/python3.7/site-packages/vistautils/parameters_only_entrypoint.py", line 43, in parameters_only_entry_point
    args=sys.argv[1:],
  File "/nas/gaia/lestat/users/cummings/miniconda/envs/covid-claims/lib/python3.7/site-packages/vistautils/parameters_only_entrypoint.py", line 73, in _real_parameters_only_entry_point
    main_method(params)
  File "/nas/home/cummings/repos/cdse-covid/cdse_covid/pegasus_pipeline/ingesters/convert_claim_json.py", line 400, in convert_json_file_to_aif
    ) = get_claim_semantics_data(af, data)
  File "/nas/home/cummings/repos/cdse-covid/cdse_covid/pegasus_pipeline/ingesters/convert_claim_json.py", line 67, in get_claim_semantics_data
    if arg_qnodes["type"]["qnode_id"] is not None:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by elizlee** [comment]
I got this as a result of #134 since none of the `type` values have entries in `type_mapping_to_qnode`
